`timescale 1ns/1ps
`include "image_params.vh"
`include "sliding_window.v"
`include "gaussian_filter.v"

// NO MANUAL CHANGES NEEDED EVER
// All parameters come from image_params.vh
// which is auto generated by prepare_image.py

module top_level_gaussian #(
    parameter IMG_WIDTH  = `GAUSS_WIDTH,
    parameter IMG_HEIGHT = `GAUSS_HEIGHT
)(
    input  wire       clk,
    input  wire       rst,
    input  wire [7:0] pixel_in,
    input  wire       pixel_valid,
    output wire [7:0] pixel_out,
    output wire       valid_out
);

    wire [7:0] w00, w01, w02;
    wire [7:0] w10, w11, w12;
    wire [7:0] w20, w21, w22;
    wire       window_valid;

    sliding_window #(
        .IMG_WIDTH (IMG_WIDTH),
        .IMG_HEIGHT(IMG_HEIGHT)
    ) sw (
        .clk        (clk),
        .rst        (rst),
        .pixel_in   (pixel_in),
        .pixel_valid(pixel_valid),
        .w00(w00), .w01(w01), .w02(w02),
        .w10(w10), .w11(w11), .w12(w12),
        .w20(w20), .w21(w21), .w22(w22),
        .window_valid(window_valid)
    );

    gaussian_filter gf (
        .clk      (clk),
        .rst      (rst),
        .p00(w00), .p01(w01), .p02(w02),
        .p10(w10), .p11(w11), .p12(w12),
        .p20(w20), .p21(w21), .p22(w22),
        .valid_in (window_valid),
        .pixel_out(pixel_out),
        .valid_out(valid_out)
    );

endmodule