# prepare_image.py
import numpy as np
from PIL import Image
import os
import sys

# ── YOUR BASE PATH
BASE_PATH = "C:/Users/ankit/8x8 Multiplier"

def prepare_image(image_path, output_txt_path):
    if not os.path.exists(image_path):
        print(f"ERROR: Image not found at {image_path}")
        sys.exit(1)

    img       = Image.open(image_path).convert("L")
    img_array = np.array(img, dtype=np.uint8)

    height, width = img_array.shape
    print(f"Image       : {image_path}")
    print(f"Size        : {width} x {height}")
    print(f"Total pixels: {width * height}")

    with open(output_txt_path, 'w') as f:
        for row in range(height):
            for col in range(width):
                f.write(f"{img_array[row, col]}\n")

    print(f"Saved to    : {output_txt_path}")
    print(f"Lines       : {width * height}")
    print("---")

    return height, width

# ── Create all folders 
os.makedirs(f"{BASE_PATH}/sim_input",        exist_ok=True)
os.makedirs(f"{BASE_PATH}/sim_output",       exist_ok=True)
os.makedirs(f"{BASE_PATH}/results",          exist_ok=True)
os.makedirs(f"{BASE_PATH}/results/gaussian", exist_ok=True)
os.makedirs(f"{BASE_PATH}/results/sobel",    exist_ok=True)
os.makedirs(f"{BASE_PATH}/8x8 Multiplier.srcs/sources_1/new",      exist_ok=True)
# ── Scan images folder automatically 
images_folder     = f"{BASE_PATH}/images"
supported_formats = ('.tif', '.tiff', '.png', 
                     '.jpg', '.jpeg', '.bmp')

all_images = sorted([
    f for f in os.listdir(images_folder)
    if f.lower().endswith(supported_formats)
])

print(f"Found {len(all_images)} images:")
for img in all_images:
    print(f"  → {img}")
print("---")

if len(all_images) < 2:
    print("ERROR: Need at least 2 images in images/ folder")
    sys.exit(1)

gaussian_image = all_images[0]
sobel_image    = all_images[1]

print(f"Using for Gaussian : {gaussian_image}")
print(f"Using for Sobel    : {sobel_image}")
print("---")

# Prepare images
h1, w1 = prepare_image(
    image_path      = f"{images_folder}/{gaussian_image}",
    output_txt_path = f"{BASE_PATH}/sim_input/gaussian_input.txt"
)

h2, w2 = prepare_image(
    image_path      = f"{images_folder}/{sobel_image}",
    output_txt_path = f"{BASE_PATH}/sim_input/sobel_input.txt"
)

# ── Save image_info.txt for Python
with open(f"{BASE_PATH}/sim_input/image_info.txt", 'w') as f:
    f.write(f"GAUSSIAN_IMAGE={gaussian_image}\n")
    f.write(f"GAUSSIAN_WIDTH={w1}\n")
    f.write(f"GAUSSIAN_HEIGHT={h1}\n")
    f.write(f"SOBEL_IMAGE={sobel_image}\n")
    f.write(f"SOBEL_WIDTH={w2}\n")
    f.write(f"SOBEL_HEIGHT={h2}\n")

# ── NEW: Write Verilog include file automatically 
# This is what makes testbench automatic
# Vivado reads this file → no manual parameter changes needed

verilog_params = f"""// image_params.vh
// AUTO GENERATED by prepare_image.py
// DO NOT EDIT MANUALLY

// CURRENT DESIGN 
// Change CURRENT_DESIGN in prepare_image.py
// then run it again to update this
`define DESIGN_NAME "PBOM8_73Y"

// Gaussian image parameters ({gaussian_image})
`define GAUSS_WIDTH  {w1}
`define GAUSS_HEIGHT {h1}
`define GAUSS_TOTAL  {w1 * h1}

// Sobel image parameters ({sobel_image})
`define SOBEL_WIDTH  {w2}
`define SOBEL_HEIGHT {h2}
`define SOBEL_TOTAL  {w2 * h2}

// File paths
`define GAUSS_INPUT  "C:/Users/ankit/8x8 Multiplier/sim_input/gaussian_input.txt"
`define SOBEL_INPUT  "C:/Users/ankit/8x8 Multiplier/sim_input/sobel_input.txt"
`define SIM_OUTPUT   "C:/Users/ankit/8x8 Multiplier/sim_output/"
"""

params_path = f"{BASE_PATH}/8x8 Multiplier.srcs/sources_1/new/image_params.vh"
with open(params_path, 'w', encoding='utf-8') as f:
    f.write(verilog_params)

print("="*55)
print("SUMMARY:")
print(f"  Gaussian : {gaussian_image} ({w1}x{h1})")
print(f"  Sobel    : {sobel_image} ({w2}x{h2})")
print("="*55)
print(f"Verilog params written to:")
print(f"  {params_path}")
print("Now go to Vivado and run simulation.")
print("No manual changes needed in testbench!")